image: alpine/edge
packages:
  - deno
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
  - 907ce8b2-6e34-47d4-839f-bf097bde15bd
environment:
  DIR: deno-omdb
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd $DIR
      set +x
      export $OMDB_API=(cat ~/OMDB_API)
      set -x
      deno task check
      deno task test
  - check_release: |
      cd $DIR
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd $DIR
      git remote add github git@github.com:timharek/deno-omdb.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
      if [ "$(git describe --exact-match --tags HEAD)" ]; then \
        git push --tags github; \
      fi

